# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:46:46+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ActivityType(Enum):
    ACTIVITY_TYPE_UNSPECIFIED = 'ACTIVITY_TYPE_UNSPECIFIED'
    PAGEVIEW = 'PAGEVIEW'
    SCREENVIEW = 'SCREENVIEW'
    GOAL = 'GOAL'
    ECOMMERCE = 'ECOMMERCE'
    EVENT = 'EVENT'


class Type(Enum):
    UNSPECIFIED_COHORT_TYPE = 'UNSPECIFIED_COHORT_TYPE'
    FIRST_VISIT_DATE = 'FIRST_VISIT_DATE'


class CustomDimension(BaseModel):
    index: Optional[int] = Field(None, description='Slot number of custom dimension.')
    value: Optional[str] = Field(
        None,
        description='Value of the custom dimension. Default value (i.e. empty string) indicates clearing sesion/visitor scope custom dimension value.',
    )


class DateRange(BaseModel):
    endDate: Optional[str] = Field(
        None, description='The end date for the query in the format `YYYY-MM-DD`.'
    )
    startDate: Optional[str] = Field(
        None, description='The start date for the query in the format `YYYY-MM-DD`.'
    )


class Dimension(BaseModel):
    histogramBuckets: Optional[List[str]] = Field(
        None,
        description='If non-empty, we place dimension values into buckets after string to int64. Dimension values that are not the string representation of an integral value will be converted to zero. The bucket values have to be in increasing order. Each bucket is closed on the lower end, and open on the upper end. The "first" bucket includes all values less than the first boundary, the "last" bucket includes all values up to infinity. Dimension values that fall in a bucket get transformed to a new dimension value. For example, if one gives a list of "0, 1, 3, 4, 7", then we return the following buckets: - bucket #1: values < 0, dimension value "<0" - bucket #2: values in [0,1), dimension value "0" - bucket #3: values in [1,3), dimension value "1-2" - bucket #4: values in [3,4), dimension value "3" - bucket #5: values in [4,7), dimension value "4-6" - bucket #6: values >= 7, dimension value "7+" NOTE: If you are applying histogram mutation on any dimension, and using that dimension in sort, you will want to use the sort type `HISTOGRAM_BUCKET` for that purpose. Without that the dimension values will be sorted according to dictionary (lexicographic) order. For example the ascending dictionary order is: "<50", "1001+", "121-1000", "50-120" And the ascending `HISTOGRAM_BUCKET` order is: "<50", "50-120", "121-1000", "1001+" The client has to explicitly request `"orderType": "HISTOGRAM_BUCKET"` for a histogram-mutated dimension.',
    )
    name: Optional[str] = Field(
        None, description='Name of the dimension to fetch, for example `ga:browser`.'
    )


class Operator(Enum):
    OPERATOR_UNSPECIFIED = 'OPERATOR_UNSPECIFIED'
    REGEXP = 'REGEXP'
    BEGINS_WITH = 'BEGINS_WITH'
    ENDS_WITH = 'ENDS_WITH'
    PARTIAL = 'PARTIAL'
    EXACT = 'EXACT'
    NUMERIC_EQUAL = 'NUMERIC_EQUAL'
    NUMERIC_GREATER_THAN = 'NUMERIC_GREATER_THAN'
    NUMERIC_LESS_THAN = 'NUMERIC_LESS_THAN'
    IN_LIST = 'IN_LIST'


class DimensionFilter(BaseModel):
    caseSensitive: Optional[bool] = Field(
        None, description='Should the match be case sensitive? Default is false.'
    )
    dimensionName: Optional[str] = Field(
        None,
        description='The dimension to filter on. A DimensionFilter must contain a dimension.',
    )
    expressions: Optional[List[str]] = Field(
        None,
        description='Strings or regular expression to match against. Only the first value of the list is used for comparison unless the operator is `IN_LIST`. If `IN_LIST` operator, then the entire list is used to filter the dimensions as explained in the description of the `IN_LIST` operator.',
    )
    not_: Optional[bool] = Field(
        None,
        alias='not',
        description='Logical `NOT` operator. If this boolean is set to true, then the matching dimension values will be excluded in the report. The default is false.',
    )
    operator: Optional[Operator] = Field(
        None,
        description='How to match the dimension to the expression. The default is REGEXP.',
    )


class Operator1(Enum):
    OPERATOR_UNSPECIFIED = 'OPERATOR_UNSPECIFIED'
    OR = 'OR'
    AND = 'AND'


class DimensionFilterClause(BaseModel):
    filters: Optional[List[DimensionFilter]] = Field(
        None,
        description='The repeated set of filters. They are logically combined based on the operator specified.',
    )
    operator: Optional[Operator1] = Field(
        None,
        description='The operator for combining multiple dimension filters. If unspecified, it is treated as an `OR`.',
    )


class ActionType(Enum):
    UNKNOWN = 'UNKNOWN'
    CLICK = 'CLICK'
    DETAILS_VIEW = 'DETAILS_VIEW'
    ADD_TO_CART = 'ADD_TO_CART'
    REMOVE_FROM_CART = 'REMOVE_FROM_CART'
    CHECKOUT = 'CHECKOUT'
    PAYMENT = 'PAYMENT'
    REFUND = 'REFUND'
    CHECKOUT_OPTION = 'CHECKOUT_OPTION'


class EcommerceType(Enum):
    ECOMMERCE_TYPE_UNSPECIFIED = 'ECOMMERCE_TYPE_UNSPECIFIED'
    CLASSIC = 'CLASSIC'
    ENHANCED = 'ENHANCED'


class EventData(BaseModel):
    eventAction: Optional[str] = Field(
        None, description="Type of interaction with the object. Eg: 'play'."
    )
    eventCategory: Optional[str] = Field(
        None,
        description="The object on the page that was interacted with. Eg: 'Video'.",
    )
    eventCount: Optional[str] = Field(
        None, description='Number of such events in this activity.'
    )
    eventLabel: Optional[str] = Field(
        None, description='Label attached with the event.'
    )
    eventValue: Optional[str] = Field(
        None, description='Numeric value associated with the event.'
    )


class GoalData(BaseModel):
    goalCompletionLocation: Optional[str] = Field(
        None, description='URL of the page where this goal was completed.'
    )
    goalCompletions: Optional[str] = Field(
        None, description='Total number of goal completions in this activity.'
    )
    goalIndex: Optional[int] = Field(
        None, description='This identifies the goal as configured for the profile.'
    )
    goalName: Optional[str] = Field(None, description='Name of the goal.')
    goalPreviousStep1: Optional[str] = Field(
        None, description='URL of the page one step prior to the goal completion.'
    )
    goalPreviousStep2: Optional[str] = Field(
        None, description='URL of the page two steps prior to the goal completion.'
    )
    goalPreviousStep3: Optional[str] = Field(
        None, description='URL of the page three steps prior to the goal completion.'
    )
    goalValue: Optional[float] = Field(None, description='Value in this goal.')


class GoalSetData(BaseModel):
    goals: Optional[List[GoalData]] = Field(
        None, description='All the goals that were reached in the current activity.'
    )


class FormattingType(Enum):
    METRIC_TYPE_UNSPECIFIED = 'METRIC_TYPE_UNSPECIFIED'
    INTEGER = 'INTEGER'
    FLOAT = 'FLOAT'
    CURRENCY = 'CURRENCY'
    PERCENT = 'PERCENT'
    TIME = 'TIME'


class Metric(BaseModel):
    alias: Optional[str] = Field(
        None,
        description='An alias for the metric expression is an alternate name for the expression. The alias can be used for filtering and sorting. This field is optional and is useful if the expression is not a single metric but a complex expression which cannot be used in filtering and sorting. The alias is also used in the response column header.',
    )
    expression: Optional[str] = Field(
        None,
        description='A metric expression in the request. An expression is constructed from one or more metrics and numbers. Accepted operators include: Plus (+), Minus (-), Negation (Unary -), Divided by (/), Multiplied by (*), Parenthesis, Positive cardinal numbers (0-9), can include decimals and is limited to 1024 characters. Example `ga:totalRefunds/ga:users`, in most cases the metric expression is just a single metric name like `ga:users`. Adding mixed `MetricType` (E.g., `CURRENCY` + `PERCENTAGE`) metrics will result in unexpected results.',
    )
    formattingType: Optional[FormattingType] = Field(
        None,
        description='Specifies how the metric expression should be formatted, for example `INTEGER`.',
    )


class Operator2(Enum):
    OPERATOR_UNSPECIFIED = 'OPERATOR_UNSPECIFIED'
    EQUAL = 'EQUAL'
    LESS_THAN = 'LESS_THAN'
    GREATER_THAN = 'GREATER_THAN'
    IS_MISSING = 'IS_MISSING'


class MetricFilter(BaseModel):
    comparisonValue: Optional[str] = Field(
        None, description='The value to compare against.'
    )
    metricName: Optional[str] = Field(
        None,
        description='The metric that will be filtered on. A metricFilter must contain a metric name. A metric name can be an alias earlier defined as a metric or it can also be a metric expression.',
    )
    not_: Optional[bool] = Field(
        None,
        alias='not',
        description='Logical `NOT` operator. If this boolean is set to true, then the matching metric values will be excluded in the report. The default is false.',
    )
    operator: Optional[Operator2] = Field(
        None,
        description='Is the metric `EQUAL`, `LESS_THAN` or `GREATER_THAN` the comparisonValue, the default is `EQUAL`. If the operator is `IS_MISSING`, checks if the metric is missing and would ignore the comparisonValue.',
    )


class Operator3(Enum):
    OPERATOR_UNSPECIFIED = 'OPERATOR_UNSPECIFIED'
    OR = 'OR'
    AND = 'AND'


class MetricFilterClause(BaseModel):
    filters: Optional[List[MetricFilter]] = Field(
        None,
        description='The repeated set of filters. They are logically combined based on the operator specified.',
    )
    operator: Optional[Operator3] = Field(
        None,
        description='The operator for combining multiple metric filters. If unspecified, it is treated as an `OR`.',
    )


class Type1(Enum):
    METRIC_TYPE_UNSPECIFIED = 'METRIC_TYPE_UNSPECIFIED'
    INTEGER = 'INTEGER'
    FLOAT = 'FLOAT'
    CURRENCY = 'CURRENCY'
    PERCENT = 'PERCENT'
    TIME = 'TIME'


class MetricHeaderEntry(BaseModel):
    name: Optional[str] = Field(None, description='The name of the header.')
    type: Optional[Type1] = Field(
        None, description='The type of the metric, for example `INTEGER`.'
    )


class OrderType(Enum):
    ORDER_TYPE_UNSPECIFIED = 'ORDER_TYPE_UNSPECIFIED'
    VALUE = 'VALUE'
    DELTA = 'DELTA'
    SMART = 'SMART'
    HISTOGRAM_BUCKET = 'HISTOGRAM_BUCKET'
    DIMENSION_AS_INTEGER = 'DIMENSION_AS_INTEGER'


class SortOrder(Enum):
    SORT_ORDER_UNSPECIFIED = 'SORT_ORDER_UNSPECIFIED'
    ASCENDING = 'ASCENDING'
    DESCENDING = 'DESCENDING'


class OrderBy(BaseModel):
    fieldName: Optional[str] = Field(
        None,
        description='The field which to sort by. The default sort order is ascending. Example: `ga:browser`. Note, that you can only specify one field for sort here. For example, `ga:browser, ga:city` is not valid.',
    )
    orderType: Optional[OrderType] = Field(
        None, description='The order type. The default orderType is `VALUE`.'
    )
    sortOrder: Optional[SortOrder] = Field(
        None, description='The sorting order for the field.'
    )


class PageviewData(BaseModel):
    pagePath: Optional[str] = Field(
        None, description='The URL of the page that the visitor viewed.'
    )
    pageTitle: Optional[str] = Field(
        None, description='The title of the page that the visitor viewed.'
    )


class Pivot(BaseModel):
    dimensionFilterClauses: Optional[List[DimensionFilterClause]] = Field(
        None,
        description='DimensionFilterClauses are logically combined with an `AND` operator: only data that is included by all these DimensionFilterClauses contributes to the values in this pivot region. Dimension filters can be used to restrict the columns shown in the pivot region. For example if you have `ga:browser` as the requested dimension in the pivot region, and you specify key filters to restrict `ga:browser` to only "IE" or "Firefox", then only those two browsers would show up as columns.',
    )
    dimensions: Optional[List[Dimension]] = Field(
        None,
        description='A list of dimensions to show as pivot columns. A Pivot can have a maximum of 4 dimensions. Pivot dimensions are part of the restriction on the total number of dimensions allowed in the request.',
    )
    maxGroupCount: Optional[int] = Field(
        None,
        description='Specifies the maximum number of groups to return. The default value is 10, also the maximum value is 1,000.',
    )
    metrics: Optional[List[Metric]] = Field(
        None,
        description='The pivot metrics. Pivot metrics are part of the restriction on total number of metrics allowed in the request.',
    )
    startGroup: Optional[int] = Field(
        None,
        description='If k metrics were requested, then the response will contain some data-dependent multiple of k columns in the report. E.g., if you pivoted on the dimension `ga:browser` then you\'d get k columns for "Firefox", k columns for "IE", k columns for "Chrome", etc. The ordering of the groups of columns is determined by descending order of "total" for the first of the k values. Ties are broken by lexicographic ordering of the first pivot dimension, then lexicographic ordering of the second pivot dimension, and so on. E.g., if the totals for the first value for Firefox, IE, and Chrome were 8, 2, 8, respectively, the order of columns would be Chrome, Firefox, IE. The following let you choose which of the groups of k columns are included in the response.',
    )


class PivotHeaderEntry(BaseModel):
    dimensionNames: Optional[List[str]] = Field(
        None, description='The name of the dimensions in the pivot response.'
    )
    dimensionValues: Optional[List[str]] = Field(
        None, description='The values for the dimensions in the pivot.'
    )
    metric: Optional[MetricHeaderEntry] = Field(
        None, description='The metric header for the metric in the pivot.'
    )


class PivotValueRegion(BaseModel):
    values: Optional[List[str]] = Field(
        None, description='The values of the metrics in each of the pivot regions.'
    )


class ProductData(BaseModel):
    itemRevenue: Optional[float] = Field(
        None, description='The total revenue from purchased product items.'
    )
    productName: Optional[str] = Field(
        None,
        description='The product name, supplied by the e-commerce tracking application, for the purchased items.',
    )
    productQuantity: Optional[str] = Field(
        None, description='Total number of this product units in the transaction.'
    )
    productSku: Optional[str] = Field(
        None, description='Unique code that represents the product.'
    )


class SamplingLevel(Enum):
    SAMPLING_UNSPECIFIED = 'SAMPLING_UNSPECIFIED'
    DEFAULT = 'DEFAULT'
    SMALL = 'SMALL'
    LARGE = 'LARGE'


class ResourceQuotasRemaining(BaseModel):
    dailyQuotaTokensRemaining: Optional[int] = Field(
        None, description='Daily resource quota remaining remaining.'
    )
    hourlyQuotaTokensRemaining: Optional[int] = Field(
        None, description='Hourly resource quota tokens remaining.'
    )


class ScreenviewData(BaseModel):
    appName: Optional[str] = Field(None, description='The application name.')
    mobileDeviceBranding: Optional[str] = Field(
        None,
        description='Mobile manufacturer or branded name. Eg: "Google", "Apple" etc.',
    )
    mobileDeviceModel: Optional[str] = Field(
        None, description='Mobile device model. Eg: "Pixel", "iPhone" etc.'
    )
    screenName: Optional[str] = Field(None, description='The name of the screen.')


class Operator4(Enum):
    OPERATOR_UNSPECIFIED = 'OPERATOR_UNSPECIFIED'
    REGEXP = 'REGEXP'
    BEGINS_WITH = 'BEGINS_WITH'
    ENDS_WITH = 'ENDS_WITH'
    PARTIAL = 'PARTIAL'
    EXACT = 'EXACT'
    IN_LIST = 'IN_LIST'
    NUMERIC_LESS_THAN = 'NUMERIC_LESS_THAN'
    NUMERIC_GREATER_THAN = 'NUMERIC_GREATER_THAN'
    NUMERIC_BETWEEN = 'NUMERIC_BETWEEN'


class SegmentDimensionFilter(BaseModel):
    caseSensitive: Optional[bool] = Field(
        None,
        description='Should the match be case sensitive, ignored for `IN_LIST` operator.',
    )
    dimensionName: Optional[str] = Field(
        None, description='Name of the dimension for which the filter is being applied.'
    )
    expressions: Optional[List[str]] = Field(
        None,
        description='The list of expressions, only the first element is used for all operators',
    )
    maxComparisonValue: Optional[str] = Field(
        None, description='Maximum comparison values for `BETWEEN` match type.'
    )
    minComparisonValue: Optional[str] = Field(
        None, description='Minimum comparison values for `BETWEEN` match type.'
    )
    operator: Optional[Operator4] = Field(
        None,
        description='The operator to use to match the dimension with the expressions.',
    )


class Operator5(Enum):
    UNSPECIFIED_OPERATOR = 'UNSPECIFIED_OPERATOR'
    LESS_THAN = 'LESS_THAN'
    GREATER_THAN = 'GREATER_THAN'
    EQUAL = 'EQUAL'
    BETWEEN = 'BETWEEN'


class Scope(Enum):
    UNSPECIFIED_SCOPE = 'UNSPECIFIED_SCOPE'
    PRODUCT = 'PRODUCT'
    HIT = 'HIT'
    SESSION = 'SESSION'
    USER = 'USER'


class SegmentMetricFilter(BaseModel):
    comparisonValue: Optional[str] = Field(
        None,
        description='The value to compare against. If the operator is `BETWEEN`, this value is treated as minimum comparison value.',
    )
    maxComparisonValue: Optional[str] = Field(
        None, description='Max comparison value is only used for `BETWEEN` operator.'
    )
    metricName: Optional[str] = Field(
        None,
        description='The metric that will be filtered on. A `metricFilter` must contain a metric name.',
    )
    operator: Optional[Operator5] = Field(
        None,
        description='Specifies is the operation to perform to compare the metric. The default is `EQUAL`.',
    )
    scope: Optional[Scope] = Field(
        None,
        description='Scope for a metric defines the level at which that metric is defined. The specified metric scope must be equal to or greater than its primary scope as defined in the data model. The primary scope is defined by if the segment is selecting users or sessions.',
    )


class MatchType(Enum):
    UNSPECIFIED_MATCH_TYPE = 'UNSPECIFIED_MATCH_TYPE'
    PRECEDES = 'PRECEDES'
    IMMEDIATELY_PRECEDES = 'IMMEDIATELY_PRECEDES'


class TransactionData(BaseModel):
    transactionId: Optional[str] = Field(
        None,
        description='The transaction ID, supplied by the e-commerce tracking method, for the purchase in the shopping cart.',
    )
    transactionRevenue: Optional[float] = Field(
        None,
        description='The total sale revenue (excluding shipping and tax) of the transaction.',
    )
    transactionShipping: Optional[float] = Field(
        None, description='Total cost of shipping.'
    )
    transactionTax: Optional[float] = Field(
        None, description='Total tax for the transaction.'
    )


class Type2(Enum):
    USER_ID_TYPE_UNSPECIFIED = 'USER_ID_TYPE_UNSPECIFIED'
    USER_ID = 'USER_ID'
    CLIENT_ID = 'CLIENT_ID'


class User(BaseModel):
    type: Optional[Type2] = Field(
        None,
        description='Type of the user in the request. The field `userId` is associated with this type.',
    )
    userId: Optional[str] = Field(
        None, description='Unique Id of the user for which the data is being requested.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Cohort(BaseModel):
    dateRange: Optional[DateRange] = Field(
        None,
        description='This is used for `FIRST_VISIT_DATE` cohort, the cohort selects users whose first visit date is between start date and end date defined in the DateRange. The date ranges should be aligned for cohort requests. If the request contains `ga:cohortNthDay` it should be exactly one day long, if `ga:cohortNthWeek` it should be aligned to the week boundary (starting at Sunday and ending Saturday), and for `ga:cohortNthMonth` the date range should be aligned to the month (starting at the first and ending on the last day of the month). For LTV requests there are no such restrictions. You do not need to supply a date range for the `reportsRequest.dateRanges` field.',
    )
    name: Optional[str] = Field(
        None,
        description='A unique name for the cohort. If not defined name will be auto-generated with values cohort_[1234...].',
    )
    type: Optional[Type] = Field(
        None,
        description='Type of the cohort. The only supported type as of now is `FIRST_VISIT_DATE`. If this field is unspecified the cohort is treated as `FIRST_VISIT_DATE` type cohort.',
    )


class CohortGroup(BaseModel):
    cohorts: Optional[List[Cohort]] = Field(
        None, description='The definition for the cohort.'
    )
    lifetimeValue: Optional[bool] = Field(
        None,
        description='Enable Life Time Value (LTV). LTV measures lifetime value for users acquired through different channels. Please see: [Cohort Analysis](https://support.google.com/analytics/answer/6074676) and [Lifetime Value](https://support.google.com/analytics/answer/6182550) If the value of lifetimeValue is false: - The metric values are similar to the values in the web interface cohort report. - The cohort definition date ranges must be aligned to the calendar week and month. i.e. while requesting `ga:cohortNthWeek` the `startDate` in the cohort definition should be a Sunday and the `endDate` should be the following Saturday, and for `ga:cohortNthMonth`, the `startDate` should be the 1st of the month and `endDate` should be the last day of the month. When the lifetimeValue is true: - The metric values will correspond to the values in the web interface LifeTime value report. - The Lifetime Value report shows you how user value (Revenue) and engagement (Appviews, Goal Completions, Sessions, and Session Duration) grow during the 90 days after a user is acquired. - The metrics are calculated as a cumulative average per user per the time increment. - The cohort definition date ranges need not be aligned to the calendar week and month boundaries. - The `viewId` must be an [app view ID](https://support.google.com/analytics/answer/2649553#WebVersusAppViews)',
    )


class DateRangeValues(BaseModel):
    pivotValueRegions: Optional[List[PivotValueRegion]] = Field(
        None, description='The values of each pivot region.'
    )
    values: Optional[List[str]] = Field(
        None, description='Each value corresponds to each Metric in the request.'
    )


class EcommerceData(BaseModel):
    actionType: Optional[ActionType] = Field(
        None, description='Action associated with this e-commerce action.'
    )
    ecommerceType: Optional[EcommerceType] = Field(
        None, description='The type of this e-commerce activity.'
    )
    products: Optional[List[ProductData]] = Field(
        None, description='Details of the products in this transaction.'
    )
    transaction: Optional[TransactionData] = Field(
        None, description='Transaction details of this e-commerce action.'
    )


class PivotHeader(BaseModel):
    pivotHeaderEntries: Optional[List[PivotHeaderEntry]] = Field(
        None, description='A single pivot section header.'
    )
    totalPivotGroupsCount: Optional[int] = Field(
        None, description='The total number of groups for this pivot.'
    )


class ReportRow(BaseModel):
    dimensions: Optional[List[str]] = Field(
        None, description='List of requested dimensions.'
    )
    metrics: Optional[List[DateRangeValues]] = Field(
        None, description='List of metrics for each requested DateRange.'
    )


class SearchUserActivityRequest(BaseModel):
    activityTypes: Optional[List[ActivityType]] = Field(
        None,
        description='Set of all activity types being requested. Only acvities matching these types will be returned in the response. If empty, all activies will be returned.',
    )
    dateRange: Optional[DateRange] = Field(
        None,
        description='Date range for which to retrieve the user activity. If a date range is not provided, the default date range is (startDate: current date - 7 days, endDate: current date - 1 day).',
    )
    pageSize: Optional[int] = Field(
        None,
        description="Page size is for paging and specifies the maximum number of returned rows. Page size should be > 0. If the value is 0 or if the field isn't specified, the request returns the default of 1000 rows per page.",
    )
    pageToken: Optional[str] = Field(
        None,
        description='A continuation token to get the next page of the results. Adding this to the request will return the rows after the pageToken. The pageToken should be the value returned in the nextPageToken parameter in the response to the [SearchUserActivityRequest](#SearchUserActivityRequest) request.',
    )
    user: Optional[User] = Field(
        None,
        description='Required. Unique user Id to query for. Every [SearchUserActivityRequest](#SearchUserActivityRequest) must contain this field.',
    )
    viewId: Optional[str] = Field(
        None,
        description='Required. The Analytics [view ID](https://support.google.com/analytics/answer/1009618) from which to retrieve data. Every [SearchUserActivityRequest](#SearchUserActivityRequest) must contain the `viewId`.',
    )


class SegmentFilterClause(BaseModel):
    dimensionFilter: Optional[SegmentDimensionFilter] = Field(
        None, description='Dimension Filter for the segment definition.'
    )
    metricFilter: Optional[SegmentMetricFilter] = Field(
        None, description='Metric Filter for the segment definition.'
    )
    not_: Optional[bool] = Field(
        None, alias='not', description='Matches the complement (`!`) of the filter.'
    )


class Activity(BaseModel):
    activityTime: Optional[str] = Field(
        None,
        description='Timestamp of the activity. If activities for a visit cross midnight and occur in two separate dates, then two sessions (one per date) share the session identifier. For example, say session ID 113472 has activity within 2019-08-20, and session ID 243742 has activity within 2019-08-25 and 2019-08-26. Session ID 113472 is one session, and session ID 243742 is two sessions.',
    )
    activityType: Optional[ActivityType] = Field(
        None, description='Type of this activity.'
    )
    appview: Optional[ScreenviewData] = Field(
        None, description='This will be set if `activity_type` equals `SCREEN_VIEW`.'
    )
    campaign: Optional[str] = Field(
        None,
        description='For manual campaign tracking, it is the value of the utm_campaign campaign tracking parameter. For AdWords autotagging, it is the name(s) of the online ad campaign(s) you use for the property. If you use neither, its value is (not set).',
    )
    channelGrouping: Optional[str] = Field(
        None,
        description="The Channel Group associated with an end user's session for this View (defined by the View's Channel Groupings).",
    )
    customDimension: Optional[List[CustomDimension]] = Field(
        None,
        description='A list of all custom dimensions associated with this activity.',
    )
    ecommerce: Optional[EcommerceData] = Field(
        None, description='This will be set if `activity_type` equals `ECOMMERCE`.'
    )
    event: Optional[EventData] = Field(
        None,
        description='This field contains all the details pertaining to an event and will be set if `activity_type` equals `EVENT`.',
    )
    goals: Optional[GoalSetData] = Field(
        None,
        description='This field contains a list of all the goals that were reached in this activity when `activity_type` equals `GOAL`.',
    )
    hostname: Optional[str] = Field(
        None, description='The hostname from which the tracking request was made.'
    )
    keyword: Optional[str] = Field(
        None,
        description='For manual campaign tracking, it is the value of the utm_term campaign tracking parameter. For AdWords traffic, it contains the best matching targeting criteria. For the display network, where multiple targeting criteria could have caused the ad to show up, it returns the best matching targeting criteria as selected by Ads. This could be display_keyword, site placement, boomuserlist, user_interest, age, or gender. Otherwise its value is (not set).',
    )
    landingPagePath: Optional[str] = Field(
        None, description="The first page in users' sessions, or the landing page."
    )
    medium: Optional[str] = Field(
        None,
        description='The type of referrals. For manual campaign tracking, it is the value of the utm_medium campaign tracking parameter. For AdWords autotagging, it is cpc. If users came from a search engine detected by Google Analytics, it is organic. If the referrer is not a search engine, it is referral. If users came directly to the property and document.referrer is empty, its value is (none).',
    )
    pageview: Optional[PageviewData] = Field(
        None,
        description='This will be set if `activity_type` equals `PAGEVIEW`. This field contains all the details about the visitor and the page that was visited.',
    )
    source: Optional[str] = Field(
        None,
        description='The source of referrals. For manual campaign tracking, it is the value of the utm_source campaign tracking parameter. For AdWords autotagging, it is google. If you use neither, it is the domain of the source (e.g., document.referrer) referring the users. It may also contain a port address. If users arrived without a referrer, its value is (direct).',
    )


class MetricHeader(BaseModel):
    metricHeaderEntries: Optional[List[MetricHeaderEntry]] = Field(
        None, description='Headers for the metrics in the response.'
    )
    pivotHeaders: Optional[List[PivotHeader]] = Field(
        None, description='Headers for the pivots in the response.'
    )


class OrFiltersForSegment(BaseModel):
    segmentFilterClauses: Optional[List[SegmentFilterClause]] = Field(
        None, description='List of segment filters to be combined with a `OR` operator.'
    )


class ReportData(BaseModel):
    dataLastRefreshed: Optional[str] = Field(
        None,
        description='The last time the data in the report was refreshed. All the hits received before this timestamp are included in the calculation of the report.',
    )
    emptyReason: Optional[str] = Field(
        None,
        description='If empty reason is specified, the report is empty for this reason.',
    )
    isDataGolden: Optional[bool] = Field(
        None,
        description='Indicates if response to this request is golden or not. Data is golden when the exact same request will not produce any new results if asked at a later point in time.',
    )
    maximums: Optional[List[DateRangeValues]] = Field(
        None,
        description='Minimum and maximum values seen over all matching rows. These are both empty when `hideValueRanges` in the request is false, or when rowCount is zero.',
    )
    minimums: Optional[List[DateRangeValues]] = Field(
        None,
        description='Minimum and maximum values seen over all matching rows. These are both empty when `hideValueRanges` in the request is false, or when rowCount is zero.',
    )
    rowCount: Optional[int] = Field(
        None, description='Total number of matching rows for this query.'
    )
    rows: Optional[List[ReportRow]] = Field(
        None,
        description="There's one ReportRow for every unique combination of dimensions.",
    )
    samplesReadCounts: Optional[List[str]] = Field(
        None,
        description='If the results are [sampled](https://support.google.com/analytics/answer/2637192), this returns the total number of samples read, one entry per date range. If the results are not sampled this field will not be defined. See [developer guide](/analytics/devguides/reporting/core/v4/basics#sampling) for details.',
    )
    samplingSpaceSizes: Optional[List[str]] = Field(
        None,
        description='If the results are [sampled](https://support.google.com/analytics/answer/2637192), this returns the total number of samples present, one entry per date range. If the results are not sampled this field will not be defined. See [developer guide](/analytics/devguides/reporting/core/v4/basics#sampling) for details.',
    )
    totals: Optional[List[DateRangeValues]] = Field(
        None,
        description='For each requested date range, for the set of all rows that match the query, every requested value format gets a total. The total for a value format is computed by first totaling the metrics mentioned in the value format and then evaluating the value format as a scalar expression. E.g., The "totals" for `3 / (ga:sessions + 2)` we compute `3 / ((sum of all relevant ga:sessions) + 2)`. Totals are computed before pagination.',
    )


class SegmentSequenceStep(BaseModel):
    matchType: Optional[MatchType] = Field(
        None,
        description='Specifies if the step immediately precedes or can be any time before the next step.',
    )
    orFiltersForSegment: Optional[List[OrFiltersForSegment]] = Field(
        None,
        description='A sequence is specified with a list of Or grouped filters which are combined with `AND` operator.',
    )


class SequenceSegment(BaseModel):
    firstStepShouldMatchFirstHit: Optional[bool] = Field(
        None,
        description='If set, first step condition must match the first hit of the visitor (in the date range).',
    )
    segmentSequenceSteps: Optional[List[SegmentSequenceStep]] = Field(
        None, description='The list of steps in the sequence.'
    )


class SimpleSegment(BaseModel):
    orFiltersForSegment: Optional[List[OrFiltersForSegment]] = Field(
        None,
        description='A list of segment filters groups which are combined with logical `AND` operator.',
    )


class UserActivitySession(BaseModel):
    activities: Optional[List[Activity]] = Field(
        None,
        description='Represents a detailed view into each of the activity in this session.',
    )
    dataSource: Optional[str] = Field(
        None,
        description='The data source of a hit. By default, hits sent from analytics.js are reported as "web" and hits sent from the mobile SDKs are reported as "app". These values can be overridden in the Measurement Protocol.',
    )
    deviceCategory: Optional[str] = Field(
        None, description='The type of device used: "mobile", "tablet" etc.'
    )
    platform: Optional[str] = Field(
        None,
        description='Platform on which the activity happened: "android", "ios" etc.',
    )
    sessionDate: Optional[str] = Field(
        None, description='Date of this session in ISO-8601 format.'
    )
    sessionId: Optional[str] = Field(None, description='Unique ID of the session.')


class ColumnHeader(BaseModel):
    dimensions: Optional[List[str]] = Field(
        None, description='The dimension names in the response.'
    )
    metricHeader: Optional[MetricHeader] = Field(
        None, description='Metric headers for the metrics in the response.'
    )


class Report(BaseModel):
    columnHeader: Optional[ColumnHeader] = Field(
        None, description='The column headers.'
    )
    data: Optional[ReportData] = Field(None, description='Response data.')
    nextPageToken: Optional[str] = Field(
        None, description='Page token to retrieve the next page of results in the list.'
    )


class SearchUserActivityResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='This token should be passed to [SearchUserActivityRequest](#SearchUserActivityRequest) to retrieve the next page.',
    )
    sampleRate: Optional[float] = Field(
        None,
        description='This field represents the [sampling rate](https://support.google.com/analytics/answer/2637192) for the given request and is a number between 0.0 to 1.0. See [developer guide](/analytics/devguides/reporting/core/v4/basics#sampling) for details.',
    )
    sessions: Optional[List[UserActivitySession]] = Field(
        None,
        description='Each record represents a session (device details, duration, etc).',
    )
    totalRows: Optional[int] = Field(
        None, description='Total rows returned by this query (across different pages).'
    )


class SegmentFilter(BaseModel):
    not_: Optional[bool] = Field(
        None,
        alias='not',
        description='If true, match the complement of simple or sequence segment. For example, to match all visits not from "New York", we can define the segment as follows: "sessionSegment": { "segmentFilters": [{ "simpleSegment" :{ "orFiltersForSegment": [{ "segmentFilterClauses":[{ "dimensionFilter": { "dimensionName": "ga:city", "expressions": ["New York"] } }] }] }, "not": "True" }] },',
    )
    sequenceSegment: Optional[SequenceSegment] = Field(
        None,
        description='Sequence conditions consist of one or more steps, where each step is defined by one or more dimension/metric conditions. Multiple steps can be combined with special sequence operators.',
    )
    simpleSegment: Optional[SimpleSegment] = Field(
        None,
        description='A Simple segment conditions consist of one or more dimension/metric conditions that can be combined',
    )


class GetReportsResponse(BaseModel):
    queryCost: Optional[int] = Field(
        None,
        description='The amount of resource quota tokens deducted to execute the query. Includes all responses.',
    )
    reports: Optional[List[Report]] = Field(
        None, description='Responses corresponding to each of the request.'
    )
    resourceQuotasRemaining: Optional[ResourceQuotasRemaining] = Field(
        None, description='The amount of resource quota remaining for the property.'
    )


class SegmentDefinition(BaseModel):
    segmentFilters: Optional[List[SegmentFilter]] = Field(
        None,
        description='A segment is defined by a set of segment filters which are combined together with a logical `AND` operation.',
    )


class DynamicSegment(BaseModel):
    name: Optional[str] = Field(None, description='The name of the dynamic segment.')
    sessionSegment: Optional[SegmentDefinition] = Field(
        None,
        description='Session Segment to select sessions to include in the segment.',
    )
    userSegment: Optional[SegmentDefinition] = Field(
        None, description='User Segment to select users to include in the segment.'
    )


class Segment(BaseModel):
    dynamicSegment: Optional[DynamicSegment] = Field(
        None, description='A dynamic segment definition in the request.'
    )
    segmentId: Optional[str] = Field(
        None,
        description='The segment ID of a built-in or custom segment, for example `gaid::-3`.',
    )


class ReportRequest(BaseModel):
    cohortGroup: Optional[CohortGroup] = Field(
        None,
        description='Cohort group associated with this request. If there is a cohort group in the request the `ga:cohort` dimension must be present. Every [ReportRequest](#ReportRequest) within a `batchGet` method must contain the same `cohortGroup` definition.',
    )
    dateRanges: Optional[List[DateRange]] = Field(
        None,
        description='Date ranges in the request. The request can have a maximum of 2 date ranges. The response will contain a set of metric values for each combination of the dimensions for each date range in the request. So, if there are two date ranges, there will be two set of metric values, one for the original date range and one for the second date range. The `reportRequest.dateRanges` field should not be specified for cohorts or Lifetime value requests. If a date range is not provided, the default date range is (startDate: current date - 7 days, endDate: current date - 1 day). Every [ReportRequest](#ReportRequest) within a `batchGet` method must contain the same `dateRanges` definition.',
    )
    dimensionFilterClauses: Optional[List[DimensionFilterClause]] = Field(
        None,
        description='The dimension filter clauses for filtering Dimension Values. They are logically combined with the `AND` operator. Note that filtering occurs before any dimensions are aggregated, so that the returned metrics represent the total for only the relevant dimensions.',
    )
    dimensions: Optional[List[Dimension]] = Field(
        None,
        description='The dimensions requested. Requests can have a total of 9 dimensions.',
    )
    filtersExpression: Optional[str] = Field(
        None,
        description='Dimension or metric filters that restrict the data returned for your request. To use the `filtersExpression`, supply a dimension or metric on which to filter, followed by the filter expression. For example, the following expression selects `ga:browser` dimension which starts with Firefox; `ga:browser=~^Firefox`. For more information on dimensions and metric filters, see [Filters reference](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filters).',
    )
    hideTotals: Optional[bool] = Field(
        None,
        description='If set to true, hides the total of all metrics for all the matching rows, for every date range. The default false and will return the totals.',
    )
    hideValueRanges: Optional[bool] = Field(
        None,
        description='If set to true, hides the minimum and maximum across all matching rows. The default is false and the value ranges are returned.',
    )
    includeEmptyRows: Optional[bool] = Field(
        None,
        description='If set to false, the response does not include rows if all the retrieved metrics are equal to zero. The default is false which will exclude these rows.',
    )
    metricFilterClauses: Optional[List[MetricFilterClause]] = Field(
        None,
        description='The metric filter clauses. They are logically combined with the `AND` operator. Metric filters look at only the first date range and not the comparing date range. Note that filtering on metrics occurs after the metrics are aggregated.',
    )
    metrics: Optional[List[Metric]] = Field(
        None,
        description='The metrics requested. Requests must specify at least one metric. Requests can have a total of 10 metrics.',
    )
    orderBys: Optional[List[OrderBy]] = Field(
        None,
        description='Sort order on output rows. To compare two rows, the elements of the following are applied in order until a difference is found. All date ranges in the output get the same row order.',
    )
    pageSize: Optional[int] = Field(
        None,
        description="Page size is for paging and specifies the maximum number of returned rows. Page size should be >= 0. A query returns the default of 1,000 rows. The Analytics Core Reporting API returns a maximum of 100,000 rows per request, no matter how many you ask for. It can also return fewer rows than requested, if there aren't as many dimension segments as you expect. For instance, there are fewer than 300 possible values for `ga:country`, so when segmenting only by country, you can't get more than 300 rows, even if you set `pageSize` to a higher value.",
    )
    pageToken: Optional[str] = Field(
        None,
        description='A continuation token to get the next page of the results. Adding this to the request will return the rows after the pageToken. The pageToken should be the value returned in the nextPageToken parameter in the response to the GetReports request.',
    )
    pivots: Optional[List[Pivot]] = Field(
        None,
        description='The pivot definitions. Requests can have a maximum of 2 pivots.',
    )
    samplingLevel: Optional[SamplingLevel] = Field(
        None,
        description='The desired report [sample](https://support.google.com/analytics/answer/2637192) size. If the the `samplingLevel` field is unspecified the `DEFAULT` sampling level is used. Every [ReportRequest](#ReportRequest) within a `batchGet` method must contain the same `samplingLevel` definition. See [developer guide](/analytics/devguides/reporting/core/v4/basics#sampling) for details.',
    )
    segments: Optional[List[Segment]] = Field(
        None,
        description='Segment the data returned for the request. A segment definition helps look at a subset of the segment request. A request can contain up to four segments. Every [ReportRequest](#ReportRequest) within a `batchGet` method must contain the same `segments` definition. Requests with segments must have the `ga:segment` dimension.',
    )
    viewId: Optional[str] = Field(
        None,
        description='The Analytics [view ID](https://support.google.com/analytics/answer/1009618) from which to retrieve data. Every [ReportRequest](#ReportRequest) within a `batchGet` method must contain the same `viewId`.',
    )


class GetReportsRequest(BaseModel):
    reportRequests: Optional[List[ReportRequest]] = Field(
        None,
        description='Requests, each request will have a separate response. There can be a maximum of 5 requests. All requests should have the same `dateRanges`, `viewId`, `segments`, `samplingLevel`, and `cohortGroup`.',
    )
    useResourceQuotas: Optional[bool] = Field(
        None,
        description='Enables [resource based quotas](/analytics/devguides/reporting/core/v4/limits-quotas#analytics_reporting_api_v4), (defaults to `False`). If this field is set to `True` the per view (profile) quotas are governed by the computational cost of the request. Note that using cost based quotas will higher enable sampling rates. (10 Million for `SMALL`, 100M for `LARGE`. See the [limits and quotas documentation](/analytics/devguides/reporting/core/v4/limits-quotas#analytics_reporting_api_v4) for details.',
    )
